import type { Metadata } from "next";
import localFont from 'next/font/local'
import HeadNavigation from "../../components/ui/HeadNavigation";
import "../globals.css";


 
const PlayfairDisplay = localFont({
  src: '../../public/fonts/PlayfairDisplay-VariableFont_wght.ttf',
  variable: '--font-pd',
},
);

const EBGaramond = localFont({
  src: '../../public/fonts/EBGaramond-VariableFont_wght.ttf',
  variable: '--font-garamond',
},
);


const IBM_Plex_Mono = localFont({
  src: '../../public/fonts/IBMPlexMono-Regular.ttf',
  variable: '--font-ibmmono',
},
);


 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
         className={`${PlayfairDisplay.variable} ${EBGaramond.variable} ${IBM_Plex_Mono.variable} antialiased`}
      >
        <header>
          <HeadNavigation />
        </header>
        {children}
      </body>
    </html>
  );
}